services:
  mit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mit-backend
    restart: unless-stopped
    depends_on:
      mit-postgres:
        condition: service_healthy
    networks:
      - barbershop_default
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "55555"
    environment:
      DB_HOST: mit-postgres
      DB_PORT: 5432
      DB_USER: green_user
      DB_PASS: green_password
      DB_DATABASE: green_cycle
      PORT: 55555

  mit-postgres:
    image: postgres:16
    container_name: mit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: green_user
      POSTGRES_PASSWORD: green_password
      POSTGRES_DB: green_cycle
    volumes:
      - mit_postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - barbershop_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U green_user -d green_cycle"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mit_postgres_data:

networks:
  barbershop_default:
    external: true